import { createClient } from '@supabase/supabase-js'
import crypto from 'crypto'
import fs from 'fs'
import path from 'path'

// Manually load env vars
const loadEnv = (filename: string) => {
    try {
        const envPath = path.resolve(__dirname, '..', filename)
        if (!fs.existsSync(envPath)) return
        const content = fs.readFileSync(envPath, 'utf-8')
        content.split('\n').forEach(line => {
            const match = line.match(/^([^=]+)=(.*)$/)
            if (match) {
                const key = match[1].trim()
                const value = match[2].trim().replace(/^["']|["']$/g, '') // remove quotes
                if (!process.env[key]) process.env[key] = value
            }
        })
    } catch (e) { }
}

loadEnv('.env.local')
loadEnv('.env')

if (!process.env.NEXT_PUBLIC_SUPABASE_URL || !process.env.SUPABASE_SERVICE_ROLE_KEY) {
    console.error('Missing env vars (checked .env.local and .env)')
    process.exit(1)
}

const supabaseAdmin = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL,
    process.env.SUPABASE_SERVICE_ROLE_KEY,
    { auth: { autoRefreshToken: false, persistSession: false } }
)

async function test() {
    console.log('--- Starting API Verification ---')

    // 1. Setup Test User & Key
    // We'll use the first user found or create a dummy one?
    // Safer to use an existing user.
    const { data: users } = await supabaseAdmin.auth.admin.listUsers()
    if (!users || users.users.length === 0) {
        console.error('No users found. Cannot test.')
        return
    }
    const user = users.users[0]
    console.log(`Using user: ${user.email} (${user.id})`)

    // Ensure user is in a team
    const { data: member } = await supabaseAdmin.from('team_members').select('team_id').eq('user_id', user.id).single()
    if (!member) {
        console.error('User not in any team.')
        // Assign to a team if possible? Skipping for now.
        return
    }
    const teamId = member.team_id
    console.log(`Using team: ${teamId}`)

    // Create Key
    const rawKey = 'sk_test_' + crypto.randomBytes(16).toString('hex')
    const keyHash = crypto.createHash('sha256').update(rawKey).digest('hex')

    const { error: insertError } = await supabaseAdmin.from('api_keys').insert({
        user_id: user.id,
        label: 'Automated Test Key',
        key_hash: keyHash
    })

    if (insertError) {
        console.error('Failed to insert test key', insertError)
        return
    }
    console.log('Created Test API Key')

    const baseUrl = 'http://localhost:3000/api/v1/tasks'

    try {
        // 2. Test GET List
        console.log(`\nTesting GET ${baseUrl}...`)
        const getRes = await fetch(`${baseUrl}?team_id=${teamId}`, {
            headers: { 'x-api-key': rawKey }
        })
        const getData = await getRes.json()
        console.log('GET Status:', getRes.status)
        if (!getData.success) console.error('GET Failed:', getData)
        else console.log(`GET Success: Found ${getData.count} tasks`)

        // 3. Test POST Create
        console.log(`\nTesting POST ${baseUrl}...`)
        const postRes = await fetch(baseUrl, {
            method: 'POST',
            headers: { 'x-api-key': rawKey, 'Content-Type': 'application/json' },
            body: JSON.stringify({
                title: 'Test Task from Script',
                description: 'Generated by verify-api.ts',
                team_id: teamId
            })
        })
        const postData = await postRes.json()
        console.log('POST Status:', postRes.status)
        if (!postData.success) {
            console.error('POST Failed:', postData)
        } else {
            console.log('POST Success:', postData.task.id)
            const taskId = postData.task.id

            // Debug: Check DB immediately
            const { data: dbTask, error: dbError } = await supabaseAdmin.from('tasks').select('id, team_id').eq('id', taskId).single()
            if (dbError || !dbTask) {
                console.error('CRITICAL: Task not found in DB immediately after POST!', dbError)
            } else {
                console.log('DEBUG: Task verified in DB:', dbTask)
            }

            // 4. Test PATCH Update
            console.log(`\nTesting PATCH ${baseUrl}/${taskId}...`)
            const patchRes = await fetch(`${baseUrl}/${taskId}`, {
                method: 'PATCH',
                headers: { 'x-api-key': rawKey, 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    title: 'Test Task UPDATED',
                    status: 'todo' // Assuming 'todo' exists or name resolution works? 
                    // Wait, name resolution logs error if not found but returns success? 
                    // Logic was: if statusId found, update.
                })
            })
            const patchData = await patchRes.json()
            console.log('PATCH Status:', patchRes.status)
            if (!patchData.success) console.error('PATCH Failed:', patchData)
            else console.log('PATCH Success')

            // 5. Test POST Comment
            console.log(`\nTesting POST Comment ${baseUrl}/${taskId}/comments...`)
            const commentRes = await fetch(`${baseUrl}/${taskId}/comments`, {
                method: 'POST',
                headers: { 'x-api-key': rawKey, 'Content-Type': 'application/json' },
                body: JSON.stringify({ content: 'Automated comment' })
            })
            const commentData = await commentRes.json()
            console.log('COMMENT Status:', commentRes.status)
            if (!commentData.success) console.error('COMMENT Failed:', commentData)
            else console.log('COMMENT Success')
        }

    } catch (e) {
        console.error('Test Execution Error:', e)
    } finally {
        // Cleanup Key
        console.log('\nCleaning up...')
        await supabaseAdmin.from('api_keys').delete().eq('key_hash', keyHash)
        console.log('Done.')
    }
}

test()
